CREATE TABLE Atendimento (id_atendimento int4 NOT NULL, id_paciente int4 NOT NULL, id_profissional int4 NOT NULL, id_departamento int4 NOT NULL, status_atendimento varchar(15) NOT NULL, data_hora date NOT NULL, PRIMARY KEY (id_atendimento));
CREATE TABLE Cargo (id_cargo SERIAL NOT NULL, nome varchar(255), descricao varchar(255), PRIMARY KEY (id_cargo));
CREATE TABLE Contatos (id_contato int4 NOT NULL, id_pessoa int4 NOT NULL, telefone varchar(15) NOT NULL UNIQUE, PRIMARY KEY (id_contato));
CREATE TABLE Departamento (id_departamento int4 NOT NULL, nome varchar(255) NOT NULL UNIQUE, PRIMARY KEY (id_departamento));
CREATE TABLE Enderecos (id_endereco int4 NOT NULL, id_pessoa int4 NOT NULL, logradouro varchar(255) NOT NULL, numero int4, bairro varchar(255) NOT NULL, cidade varchar(255) NOT NULL, estado varchar(2), cep varchar(8), PRIMARY KEY (id_endereco));
CREATE TABLE Especialidade (id_especialidade int4 NOT NULL, nome varchar(255) NOT NULL UNIQUE, PRIMARY KEY (id_especialidade));
CREATE TABLE "Exame Solicitado" (id_exame int4 NOT NULL, id_atendimento int4 NOT NULL, nome_exame varchar(255) NOT NULL, data_solicitacao date NOT NULL, data_realizacao date, status varchar(20) NOT NULL, laudo varchar(255), PRIMARY KEY (id_exame));
CREATE TABLE "Historico Ocupacao" (id_historico SERIAL NOT NULL, id_internacao int4 NOT NULL, id_numero_leito varchar(10) NOT NULL, data_inicio date NOT NULL, data_fim date NOT NULL, PRIMARY KEY (id_historico));
CREATE TABLE Internacoes (id_internacao SERIAL NOT NULL, id_atendimento int4 NOT NULL, id_paciente int4 NOT NULL, data_hora_entrada date NOT NULL, data_prevista_alta date NOT NULL, data_efetivada_alta date, diagnostico_admissao varchar(255) NOT NULL, PRIMARY KEY (id_internacao));
CREATE TABLE Leito (id_numero_leito varchar(10) NOT NULL, id_departamento int4 NOT NULL, status varchar(20) NOT NULL, PRIMARY KEY (id_numero_leito));
CREATE TABLE Medicamento (id_medicamento int4 NOT NULL, principio_ativo varchar(255) NOT NULL, nome_comercial varchar(255) NOT NULL, fabricante varchar(255) NOT NULL, Prescricoesid_prescricoes int4 NOT NULL, PRIMARY KEY (id_medicamento));
CREATE TABLE Paciente (id_paciente int4 NOT NULL, id_pessoa int4 NOT NULL, PRIMARY KEY (id_paciente));
CREATE TABLE Pessoa (id_pessoa int4 NOT NULL, nome_completo varchar(255) NOT NULL, data_nascimento date NOT NULL, cpf varchar(11) NOT NULL UNIQUE, email varchar(255) NOT NULL UNIQUE, status_ativo int2 DEFAULT 1, PRIMARY KEY (id_pessoa));
CREATE TABLE Prescricoes (id_prescricoes int4 NOT NULL, id_atendimento int4 NOT NULL, id_medicamento int4 NOT NULL, posologia varchar(255) NOT NULL, PRIMARY KEY (id_prescricoes));
CREATE TABLE Profissional (id_profissional int4 NOT NULL, id_pessoa int4 NOT NULL, id_departamento int4 NOT NULL, id_especialidade int4 NOT NULL, id_cargo int4 NOT NULL, numero_conselho int4, PRIMARY KEY (id_profissional));
ALTER TABLE Contatos ADD CONSTRAINT FKContatos655083 FOREIGN KEY (id_pessoa) REFERENCES "Pessoa " (id_pessoa);
ALTER TABLE Enderecos ADD CONSTRAINT FKEnderecos573212 FOREIGN KEY (id_pessoa) REFERENCES "Pessoa " (id_pessoa);
ALTER TABLE Paciente ADD CONSTRAINT FKPaciente928608 FOREIGN KEY (id_pessoa) REFERENCES "Pessoa " (id_pessoa);
ALTER TABLE Profissional ADD CONSTRAINT FKProfission159710 FOREIGN KEY (id_pessoa) REFERENCES "Pessoa " (id_pessoa);
ALTER TABLE Atendimento ADD CONSTRAINT FKAtendiment759047 FOREIGN KEY (id_paciente) REFERENCES Paciente (id_paciente);
ALTER TABLE Atendimento ADD CONSTRAINT FKAtendiment987673 FOREIGN KEY (id_profissional) REFERENCES Profissional (id_profissional);
ALTER TABLE Atendimento ADD CONSTRAINT FKAtendiment69333 FOREIGN KEY (id_departamento) REFERENCES Departamento (id_departamento);
ALTER TABLE Profissional ADD CONSTRAINT FKProfission205070 FOREIGN KEY (id_especialidade) REFERENCES Especialidade (id_especialidade);
ALTER TABLE Profissional ADD CONSTRAINT FKProfission24987 FOREIGN KEY (id_departamento) REFERENCES Departamento (id_departamento);
ALTER TABLE Profissional ADD CONSTRAINT FKProfission924783 FOREIGN KEY (id_cargo) REFERENCES Cargo (id_cargo);
ALTER TABLE Internacoes ADD CONSTRAINT FKInternacoe934002 FOREIGN KEY (id_atendimento) REFERENCES Atendimento (id_atendimento);
ALTER TABLE Internacoes ADD CONSTRAINT FKInternacoe301169 FOREIGN KEY (id_paciente) REFERENCES Paciente (id_paciente);
ALTER TABLE Leito ADD CONSTRAINT FKLeito622543 FOREIGN KEY (id_departamento) REFERENCES Departamento (id_departamento);
ALTER TABLE "Historico Ocupacao" ADD CONSTRAINT "FKHistorico 212374" FOREIGN KEY (id_internacao) REFERENCES Internacoes (id_internacao);
ALTER TABLE "Historico Ocupacao" ADD CONSTRAINT "FKHistorico 324132" FOREIGN KEY (id_numero_leito) REFERENCES Leito (id_numero_leito);
ALTER TABLE Prescricoes ADD CONSTRAINT FKPrescricoe30657 FOREIGN KEY (id_atendimento) REFERENCES Atendimento (id_atendimento);